apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-suggestion-random
  namespace: kubeflow
  labels:
    app: katib
    component: suggestion-random
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katib
      component: suggestion-random
  template:
    metadata:
      name: katib-suggestion-random
      labels:
        app: katib
        component: suggestion-random
    spec:
      containers:
      - name: katib-suggestion-random
        image: gcr.io/kubeflow-images-public/katib/v1alpha2/suggestion-random
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 6789
