apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: katib-manager
  namespace: kubeflow
  labels:
    app: katib
    component: manager
spec:
  replicas: 1
  template:
    metadata:
      name: katib-manager
      labels:
        app: katib
        component: manager
    spec:
      containers:
      - name: katib-manager
        image: katib/v1alpha2/katib-manager:1
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: katib-db-secrets
                key: MYSQL_ROOT_PASSWORD
        command:
          - './katib-manager'
        ports:
        - name: api
          containerPort: 6789
