apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-bayesianoptimization
  namespace: kubeflow
  labels:
    app: vizier
    component: suggestion-bayesianoptimization
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-bayesianoptimization
      labels:
        app: vizier
        component: suggestion-bayesianoptimization
    spec:
      containers:
      - name: vizier-suggestion-bayesianoptimization
        image: katib/suggestion-bayesianoptimization:local
        ports:
        - name: api
          containerPort: 6789
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: SEARCH_ALGORITHM
          value: bayesian_optimization
