apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Namespace.
  - namespace.yaml
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib UI.
  - ../../components/ui/
  # Katib webhooks.
  - ../../components/webhook/
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newTag: latest
    newName: docker.io/kubeflowkatib/katib-controller
  - name: docker.io/kubeflowkatib/katib-db-manager
    newTag: latest
    newName: docker.io/kubeflowkatib/katib-db-manager
  - name: docker.io/kubeflowkatib/katib-ui
    newTag: latest
    newName: docker.io/kubeflowkatib/katib-ui
  - name: docker.io/kubeflowkatib/cert-generator
    newTag: latest
    newName: docker.io/kubeflowkatib/cert-generator
patchesStrategicMerge:
  - ../katib-standalone/katib-config-patch.yaml
  - db-manager-patch.yaml
# Modify katib-mysql-secrets with parameters for the DB.
secretGenerator:
  - name: katib-mysql-secrets
    envs:
      - secrets.env
