name: mnist-demo
owner: katib
optimizationtype: 2
optimizationgoal: 0.99
parameterconfigs:
  configs:
  - name: --lr
    parametertype: 1
    feasible:
      min: "0.01"
      max: "0.03"
  - name: --num-layers
    parametertype: 2
    feasible:
      min: "2"
      max: "5"
  - name: --optimizer
    parametertype: 4
    feasible:
      list:
      - sgd
      - adam
      - ftrl
  - name: --num-epochs
    parametertype: 2
    feasible:
      min: "20"
      max: "20"
objectivevaluename: Validation-accuracy

