---
apiVersion: v1
kind: ConfigMap
metadata:
  name: katib-config
  namespace: kubeflow
data:
  metrics-collector-sidecar: |-
    {
      "StdOut": {
        "image": "docker.io/kubeflowkatib/file-metrics-collector:v0.15.0"
      },
      "File": {
        "image": "docker.io/kubeflowkatib/file-metrics-collector:v0.15.0"
      },
      "TensorFlowEvent": {
        "image": "docker.io/kubeflowkatib/tfevent-metrics-collector:v0.15.0",
        "resources": {
          "limits": {
            "memory": "1Gi"
          }
        }
      }
    }
  suggestion: |-
    {
      "random": {
        "image": "docker.io/kubeflowkatib/suggestion-hyperopt:v0.15.0"
      },
      "tpe": {
        "image": "docker.io/kubeflowkatib/suggestion-hyperopt:v0.15.0"
      },
      "grid": {
        "image": "docker.io/kubeflowkatib/suggestion-optuna:v0.15.0"
      },
      "hyperband": {
        "image": "docker.io/kubeflowkatib/suggestion-hyperband:v0.15.0"
      },
      "bayesianoptimization": {
        "image": "docker.io/kubeflowkatib/suggestion-skopt:v0.15.0"
      },
      "cmaes": {
        "image": "docker.io/kubeflowkatib/suggestion-goptuna:v0.15.0"
      },
      "sobol": {
        "image": "docker.io/kubeflowkatib/suggestion-goptuna:v0.15.0"
      },
      "multivariate-tpe": {
        "image": "docker.io/kubeflowkatib/suggestion-optuna:v0.15.0"
      },
      "enas": {
        "image": "docker.io/kubeflowkatib/suggestion-enas:v0.15.0",
        "resources": {
          "limits": {
            "memory": "200Mi"
          }
        }
      },
      "darts": {
        "image": "docker.io/kubeflowkatib/suggestion-darts:v0.15.0"
      },
      "pbt": {
        "image": "docker.io/kubeflowkatib/suggestion-pbt:v0.15.0",
        "persistentVolumeClaimSpec": {
          "accessModes": [
            "ReadWriteMany"
          ],
          "resources": {
            "requests": {
              "storage": "5Gi"
            }
          }
        }
      }
    }
  early-stopping: |-
    {
      "medianstop": {
        "image": "docker.io/kubeflowkatib/earlystopping-medianstop:v0.15.0"
      }
    }
