---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katib-controller
# Please fix your infrastructure. A lot of workflows fail because of docker rate limits.
# We only need the verb create and not delete because all things are owned transitively by the
# experiment, so everything is cascade-deleted on experiment deletion.
# Early stopping currently creates a serviceaccount, role and rolebinding to manage trials and trails/status.
# The roles and rolebinding creation is the most important potential security issue now.
# Via new roles, rolebindings and pods in kubernetes system namespaces the cluster 
# could become compromised if katib-controller is compromised.
rules:
  - apiGroups:
      - ""
      - apps
      - rbac.authorization.k8s.io
    resources:
      - services # suggestion-api and earlystopping-api
      - events # katib cries is you remove it for unknown reasons
      - persistentvolumeclaims # maybe katib creates volumes, i am not sure
      - deployments # the main deployment that serves suggestion-api and earlystopping-api
      - pods # maybe to tfjobs etc. I  am not sure
      - pods/log # maybe to tfjobs etc. I  am not sure
      - pods/status # maybe to tfjobs etc. I  am not sure
      - jobs # trials are executed via jobs
      - cronjobs # i do not know why it is there. maybe you can delay trials
      - serviceaccounts # earlystopping
      - roles # earlystopping
      - rolebindings # earlystopping
    verbs:
      - get
      - list
      - watch
      - patch
      - create
  - apiGroups:
      - batch
    resources:
      - jobs # trials are executed via jobs
      - cronjobs # i do not know why it is there. maybe you can delay trials
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - delete # this is essential
  - apiGroups:
      - ""
    resources:
      - configmaps # i do not have a clue
      - persistentvolumes # i do not have a clue
      - namespaces 
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources: # everything here is obvious
      - experiments
      - experiments/status
      - experiments/finalizers
      - trials
      - trials/status
      - trials/finalizers
      - suggestions
      - suggestions/status
      - suggestions/finalizers
      - tfjobs
      - pytorchjobs
      - mpijobs
      - xgboostjobs
      - mxjobs
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: katib-controller
  namespace: kubeflow
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katib-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: katib-controller
subjects:
  - kind: ServiceAccount
    name: katib-controller
    namespace: kubeflow
