apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Katib controller.
  - ../../components/controller/controller.yaml
  - ../../components/controller/service.yaml
  - ../../components/controller/rbac.yaml
  - ../../components/controller/katib-config.yaml
  - ../../components/controller/trial-templates.yaml
  # Katib CRDs.
  - ../../components/crd/experiment.yaml
  - ../../components/crd/suggestion.yaml
  - ../../components/crd/trial.yaml
  # Katib DB manager.
  - ../../components/db-manager/db-manager.yaml
  - ../../components/db-manager/service.yaml
  # Katib DB mysql.
  - ../../components/mysql/mysql.yaml
  - ../../components/mysql/service.yaml
  - ../../components/mysql/pvc.yaml
  - ../../components/mysql/secret.yaml
  # Katib UI.
  - ../../components/ui/ui.yaml
  - ../../components/ui/service.yaml
  - ../../components/ui/rbac.yaml
  # Katib webhooks.
  - ../../components/webhook/webhooks.yaml
  # Cert-manager certificate for webhooks
  - certificate.yaml
  # Kubeflow Katib components.
  - ../katib-with-kubeflow/kubeflow-katib-roles.yaml
  - ../katib-with-kubeflow/ui-virtual-service.yaml
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-controller
  - name: docker.io/kubeflowkatib/katib-db-manager
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-db-manager
  - name: docker.io/kubeflowkatib/katib-ui
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-ui
  - name: docker.io/kubeflowkatib/cert-generator
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/cert-generator

patchesStrategicMerge:
  - ../katib-standalone/katib-config-patch.yaml
  - patches/katib-cert-injection.yaml

patchesJson6902:
  - path: ../katib-with-kubeflow/patches/mysql-pvc.yaml
    target:
      version: v1
      name: katib-mysql
      kind: PersistentVolumeClaim
      namespace: kubeflow

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: KATIB_UI_NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: katib-ui
- fieldref:
    fieldPath: metadata.namespace
  name: KATIB_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: katib-controller
- fieldref:
    fieldPath: metadata.name
  name: KATIB_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: katib-controller
- name: KATIB_CERT_NAME
  objref:
      kind: Certificate
      group: cert-manager.io
      version: v1alpha2
      name: katib-webhook-cert
  fieldref:
    fieldpath: metadata.name

configurations:
  - params.yaml
