apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-core
  namespace: katib
  labels:
    app: vizier
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-core
      labels:
        app: vizier
        component: core
    spec:
      serviceAccountName: vizier-core
      containers:
      - name: vizier-core
        image: katib/vizier-core
        command:
          - './vizier-manager'
          - "-w"
          - "kubernetes"
          - "-i"
          - "k-cluster.osrg.net"
        ports:
        - name: api
          containerPort: 6789
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
