apiVersion: v1
kind: Service
metadata:
  name: vizier-core
  namespace: katib
  labels:
    app: vizier
    component: core
spec:
  type: NodePort
  ports:
    - port: 6789
      protocol: TCP
      nodePort: 30678
      name: api
  selector:
    app: vizier
    component: core
