apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-nasenvelopenet
  namespace: kubeflow
  labels:
    app: vizier
    component: suggestion-nasenvelopenet
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-nasenvelopenet
      labels:
        app: vizier
        component: suggestion-nasenvelopenet
    spec:
      containers:
      - name: vizier-suggestion-nasenvelopenet
        image: katib/suggestion-nasenvelopenet
        ports:
        - name: api
          containerPort: 6789
