apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-nasrl
  namespace: kubeflow
  labels:
    app: vizier
    component: suggestion-nasrl
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-nasrl
      labels:
        app: vizier
        component: suggestion-nasrl
    spec:
      containers:
      - name: vizier-suggestion-nasrl
        image: katib/suggestion-nasrl
        ports:
        - name: api
          containerPort: 6789