apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: katib-suggestion-hyperband
  namespace: kubeflow
  labels:
    app: katib
    component: suggestion-hyperband
spec:
  replicas: 1
  template:
    metadata:
      name: katib-suggestion-hyperband
      labels:
        app: katib
        component: suggestion-hyperband
    spec:
      containers:
      - name: katib-suggestion-hyperband
        image: gcr.io/kubeflow-images-public/katib/v1alpha3/suggestion-hyperband
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 6789
