apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-hyperband
  namespace: katib
  labels:
    app: vizier
    component: suggestion-hyperband
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-hyperband
      labels:
        app: vizier
        component: suggestion-hyperband
    spec:
      containers:
      - name: vizier-suggestion-hyperband
        image: katib/suggestion-hyperband
        ports:
        - name: api
          containerPort: 6789
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
