name: E2E Test with pytorch-mnist

on:
  pull_request:
    paths-ignore:
      - "pkg/ui/v1beta1/frontend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}
          python-version: "3.10"

      - name: Run e2e test with ${{ matrix.experiments }} experiments
        uses: ./.github/workflows/template-e2e-test
        with:
          experiments: ${{ matrix.experiments }}
          training-operator: true
          # Comma Delimited
          trial-images: pytorch-mnist-cpu

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["v1.30.7", "v1.31.3", "v1.32.2"]
        # Comma Delimited
        experiments:
          # suggestion-hyperopt
          - "long-running-resume,from-volume-resume,median-stop"
          # others
          - "grid,bayesian-optimization,tpe,multivariate-tpe,cma-es,hyperband"
          - "hyperopt-distribution,optuna-distribution"
          - "file-metrics-collector,pytorchjob-mnist"
          - "median-stop-with-json-format,file-metrics-collector-with-json-format"
