name: E2E Test with Katib UI, random search, and postgres

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}

      - name: Run e2e test with ${{ matrix.experiments }} experiments
        uses: ./.github/workflows/template-e2e-test
        with:
          experiments: random
          # Comma Delimited
          trial-images: pytorch-mnist-cpu
          katib-ui: true
          database-type: postgres

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["v1.30.7", "v1.31.3", "v1.32.2"]
