name: E2E Test with mxnet-mnist
on:
  pull_request:
    paths-ignore:
      - "pkg/new-ui/v1beta1/frontend/**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}

      - name: Run e2e test with ${{ matrix.experiments }} experiments
        uses: ./.github/workflows/template-e2e-test
        with:
          experiments: ${{ matrix.experiments }}
          # Comma Delimited
          trial-images: mxnet-mnist

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["v1.23.13", "v1.24.7", "v1.25.3"]
        # Comma Delimited
        experiments:
          # suggestion-hyperopt
          - "never-resume,from-volume-resume,median-stop"
          # others
          - "grid,bayesian-optimization,tpe,multivariate-tpe,cma-es,hyperband"
