name: E2E Test with tf-mnist-with-summaries
on:
  - pull_request

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}

      - name: Run e2e test with ${{ matrix.experiments }} experiments
        uses: ./.github/workflows/template-e2e-test
        with:
          experiments: ${{ matrix.experiments }}
          training-operator: true
          # Comma Delimited
          trial-images: tf-mnist-with-summaries

    strategy:
      fail-fast: false
      matrix:
        # Detail: https://hub.docker.com/r/kindest/node
        # TODO (tenzen-y): We need to consider running tests on more kubernetes versions.
        # kubernetes-version: ["v1.20.15", "v1.21.12", "v1.22.9", "v1.23.6", "v1.24.1"]
        kubernetes-version: ["v1.21.12", "v1.22.9", "v1.23.6"]
        # Comma Delimited
        experiments: ["tfjob-mnist-with-summaries"]
